[package]
name = "stun_3478"
version = "0.0.1"
authors = ["Toshiya Nakakura <nakakura@me.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.7"
failure = "0.1.3"
futures = "0.1.25"
nom = "4.1.1"
pnet = "0.21.0"
rand = "0.5.5"
tokio = "0.1.13"

[dev-dependencies]
hex = "0.3.2"
